---
title: "TVP для отчаявшихся что-то понять"
author: "Boris Demeshev, Oxana Malakhovskaya"
date: "3 March 2017"
output: pdf_document
lang: ru-RU
---

# Модель

# Априорные распределения

# Эмпирическая оценка гиперпараметров

# Фильтр Калмана

# Алгоритм Картера-Кона

FAQ:

- Чем Картер-Кон отличается от сглаживания Калмана?

- Сглаживание Калмана позволяет найти:
$E(\beta_1 | \tilde y_T)$, $E(\beta_2 | \tilde y_T)$, ...
$Var(\beta_1 | \tilde y_T)$, $Var(\beta_2 | \tilde y_T)$, ...

Математических ожиданий достаточно, чтобы найти $\E(\tilde \beta_T|\tilde y_T)$. Однако отдельных ковариационных матриц $\Var(\beta_t | \tilde y_T)$ недостаточно, чтобы посчитать $\Var(\tilde\beta_T | \tilde y_T)$, так как нужны ещё всякие ковариации типа $\Cov(\beta_1, \beta_2 | \tilde y_T)$. 

А для генерирования выборки из распределения $\tilde \beta_T | \tilde y_T$ нужны и $\E(\tilde \beta_T|\tilde y_T)$ и $\Var(\tilde\beta_T | \tilde y_T)$. Алгоритм Картера-Кона генерирует выборку из $\tilde \beta_T | \tilde y_T$ не находя явно эти две здоровые матрицы.

# Kim, Shephard, and Chib

# В бой!






